### ISSUE TITLE
richdem v2.3.1

### ISSUE THREAD

**Issue by jayqi** [conda-forge/richdem-feedstock#25]
The current release of richdem is v2.3.1, but this feedstock only has v2.3.0. Would it be possible to get v2.3.1 released? Thanks in advance.

**Comment by ocefpaf** [comment]
See https://github.com/conda-forge/richdem-feedstock/pull/14

**Comment by jayqi** [comment]
Ah, I didn't see that PR. Thanks for linking. In that case, I think v2.3.0 may be good enough then.
